module.exports={
    DATABASE_STORE_ERR:'DATABASE_INSERTION_ERR',
    DATABASE_READ_ERR:'DATABASE_READ_ERR',
    DATABASE_DELETE_ERR:'DATABASE_DELETE_ERR',
    DATABASE_INSERTION_SUCCESS:'DATABASE_INSERTION_SUCCESS',
    DATABASE_DELETE_SUCCESS:'DATABASE_DELETE_SUCCESS',
    RETRY_CONSTANT: 5,
    VALIDATION_SUCCESS:'VALIDATION_SUCCESS',
    VALIDATION_FAILURE:'VALIDATION_FAILURE'
}